export const RESEARCH_AREAS = [
  "AI_RESEARCH",
  "CLIMATE_RESEARCH",
  "HEALTH_RESEARCH",
  "EDUCATION_RESEARCH",
  "ENGINEERING_RESEARCH",
  "SOCIAL_SCIENCE",
  "PUBLIC_POLICY",
  "OPEN_SOURCE_RESEARCH",
  "ECONOMICS",
  "ENERGY_RESEARCH",
  "AGRICULTURE",
  "HUMANITIES",
  "INTERDISCIPLINARY",
  "OTHER",
] as const;

export const ROUND_STATUSES = [
  "DRAFT", "OPEN", "CLOSED", "UNDER_REVIEW", "RANKED",
  "AWARDS_ASSIGNED", "APPEALS_OPEN", "FINALIZED", "ARCHIVED",
] as const;

export const PROPOSAL_STATUSES = [
  "DRAFT", "SUBMITTED", "EVIDENCE_PENDING", "UNDER_CONSENSUS_REVIEW",
  "RECOMMENDED_FOR_FUNDING", "PARTIAL_FUNDING_RECOMMENDED", "WAITLISTED",
  "REJECTED", "NEEDS_MORE_EVIDENCE", "ESCALATED", "APPEALED",
  "MILESTONE_ACTIVE", "FINALIZED",
] as const;

export const EVIDENCE_TYPES = [
  "PROPOSAL_DOCUMENT", "CV", "PUBLICATION", "DATASET", "GITHUB_REPOSITORY",
  "PRIOR_RESEARCH", "PILOT_STUDY_RESULT", "BUDGET_SHEET", "MILESTONE_PLAN",
  "ETHICS_DOCUMENT", "INSTITUTIONAL_AFFILIATION", "LETTER_OF_SUPPORT",
  "FIELDWORK_PLAN", "COMMUNITY_NEED_EVIDENCE", "PORTFOLIO", "MEDIA_LINK",
  "ONCHAIN_ACTIVITY", "OTHER",
] as const;

export const RUBRIC_CATEGORIES = [
  "RESEARCH_RELEVANCE", "ORIGINALITY", "METHODOLOGY_QUALITY", "FEASIBILITY",
  "EXPECTED_IMPACT", "APPLICANT_CAPABILITY", "BUDGET_REASONABLENESS",
  "MILESTONE_CLARITY", "ETHICS_AND_RISK", "EVIDENCE_STRENGTH",
] as const;

export const APPEAL_REASONS = [
  "EVIDENCE_NOT_CONSIDERED", "RUBRIC_MISAPPLIED", "METHODOLOGY_MISJUDGED",
  "IMPACT_MISJUDGED", "BUDGET_MISJUDGED", "ELIGIBILITY_MISINTERPRETED",
  "NEW_EVIDENCE_AVAILABLE", "RANKING_ERROR", "OTHER",
] as const;
